### ISSUE TITLE
Power loss tolerant durability

### ISSUE THREAD

**Issue by bluestreak01** [questdb/roadmap#2]
## Summary

This is a building block of `replication` and a pillar of fault tolerance in a database. 

## Intended outcome

`_txn` and `_meta` file updates will be fault tolerant in cases of complete power failures. Replication will be able to perform _final_ commit with extremely limited chance of failure.

## How will it work

Both `_meta` and `_txn` will be handled the same. Each file will contain two copies of payload with a switch a 0 offset pointing to either of the two. New transaction will be updating _the passive_ payload and after update is complete and persisted they update the switch atomically.

**Comment by puzpuzpuz** [comment]
I suggest to rename this issue to something like "Two-phase metadata file updates" or "Power loss durability". That's because two-phase commit is a well-known term in distributed systems and that's not what we imply here: https://en.wikipedia.org/wiki/Two-phase_commit_protocol
