### ISSUE TITLE
Partition by hour

### ISSUE THREAD

**Issue by bluestreak01** [questdb/roadmap#20]
## Summary

In some cases daily data volumes can exceed manageable block sizes. For example ingesting 10Bn records daily could put strain on O3 algorithm. It would be prudent to divide daily data further, perhaps hours or even minutes.

## Expected outcome

New partition classifier such as `HOUR`. The data would be automatically partitioned into directories formatted as `YYYT-MM-DDTHH`.

**Comment by bsmth** [comment]
This was done in https://github.com/questdb/questdb/pull/1571

**Comment by puzpuzpuz** [comment]
This one was released in 6.1.2, so we could close the issue.

**Comment by bluestreak01** [comment]
We add “shipped” label instead

**Comment by lucgirardin** [comment]
For my purpose, it would be useful to by able to partition by week!

**Comment by gabrielmocan** [comment]
> For my purpose, it would be useful to by able to partition by week!

It is possible, docs were updated recently.
