### ISSUE TITLE
Kafka Connect Sink implementation via ILP

### ISSUE THREAD

**Issue by tris0laris** [questdb/roadmap#37]
## Summary

Users can already ingest data to QuestDB from Kafka via JDBC connector. However, there is no implementation for our fastest ingestion protocol, ILP via TCP. 

This is a Kafka Connect Sink implementation. It allows feeding data from Kafka broker to QuestDB via ILP. It embeds the Java ILP client. 

## Do you need this feature?
If this is interesting/important/critical to your use case, share your feedback with us by commenting below. Thank you!

**Comment by postol** [comment]
Did you guys think about the same for Solace PubSub+ ? Should be very similar so not difficult to support if you already have such functionality for Kafka.
