### ISSUE TITLE
Enable Deduplication for varchar column type

### ISSUE THREAD

**Issue by tris0laris** [questdb/roadmap#76]
There is an option to enable storage-level data deduplication on a table. Data deduplication works on all the data inserted into the table and replaces matching rows with the new versions. Only new rows that do no match existing data will be inserted.

As of today, Columns of VARCHAR, STRING and BINARY types cannot be used in the UPSERT KEYS list.

VARCHAR is due to be included in the UPSERT KEYS list to allow the following syntax:

CREATE TABLE TICKER_PRICE (
    ts TIMESTAMP,
    property VARCHAR,
    price DOUBLE
) TIMESTAMP(ts) PARTITION BY DAY WAL
DEDUP UPSERT KEYS(ts, property);

**Comment by nwoolmer** [comment]
Combined with this issue: https://github.com/orgs/questdb/projects/1/views/5?filterQuery=deduplication&pane=issue&itemId=73650526
